### ISSUE TITLE
调用XsdFile创建POSCAR的问题

### ISSUE THREAD

**Issue by Li-Kezhi** [PytLab/VASPy#1]
您好！这几天在学习VASP，看到您提供的代码，觉得挺好的，想试用一下。但是发现按照您的scripts里边的例子，调用XsdFile类创建POSCAR时候，出现了两个问题。

* 您的这个代码不能识别P1群之外的其他空间群吗？我发现如果我用Materials Studio 7.0创建的.xsd文件，如果不是P1群，生成的POSCAR就缺对称原子。

* 创建的POSCAR总是缺第一个原子。比如我用了一个Na8Cl8的.xsd晶胞做测试，发现得到的POSCAR漏掉了原点处的那个Na原子。

我用的Python是2.7版本，MS是7.0版本，用的操作系统是Win10 (32-bit)。因为您提供的.xsd测试文件是8.0版本，我的MS打不开，所以没法测试。附件是MS7.0生成的NaCl文件，我改写的Windows版本的POSCAR生成的Python脚本以及生成的POSCAR，可以看见POSCAR里边缺了原点处的Na原子。想请教一下是哪里出了问题？十分感谢！

[test.zip](https://github.com/PytLab/VASPy/files/549911/test.zip)

**Comment by PytLab** [comment]
你好, Li-Kezhi

1. 对于第一个问题，生成POSCAR内容我是直接按照xsd文件里的原子信息进行解析的，脚本并不会做空间群的处理，所以MaterialStudio里面是Na4Cl4的xsd里面也应该有8个原子。我看你打包的文件里的`.xsd`文件信息的确是只有Na4Cl4，并不是Na8Cl8这样，相应生成的POSCAR正常应该是总共8个原子。
![qq 20161026152643](https://cloud.githubusercontent.com/assets/8553710/19716914/b6ffde9c-9b90-11e6-808f-8c04eae303ff.png)

2. 第二个问题是***VASPy***程序的bug，不知道是不是MS的原因，晶胞的`xsd`文件中的原点的坐标并没有在文件中。这个bug已经在刚刚的提交中修复了，你可以下载最新版本的再试一下。你提供的文件也加入到了单元测试的测试数据文件中`/tests/testdata/bulk.xsd`。

非常感谢你提交的bug，如果还有其他问题欢迎提出 ^_^

Shao Zhengjiang

**Comment by Li-Kezhi** [comment]
好的，谢谢！
